name: Build Tests
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y qt6-declarative-dev-tools
      - name: Run build tests
        run: |
          ./tests/build.sh
